
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yanda
 */
public class FormBeratBadan extends javax.swing.JFrame {

    /**
     * Creates new form FormBeratBadan
     */
    public FormBeratBadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        l = new javax.swing.JRadioButton();
        w = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cobalagi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hbi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Cek Ideal Tubuh");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 120, 14);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 90, 30);

        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 90, 30);

        jLabel4.setText("Berat Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 90, 30);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 154, 80, 30);
        jPanel1.add(n);
        n.setBounds(120, 30, 310, 30);
        jPanel1.add(t);
        t.setBounds(120, 70, 310, 30);
        jPanel1.add(b);
        b.setBounds(120, 110, 310, 30);

        l.setText("Laki - Laki");
        jPanel1.add(l);
        l.setBounds(110, 150, 130, 40);

        w.setText("Perempuan");
        jPanel1.add(w);
        w.setBounds(250, 150, 120, 40);

        hitung.setText("Hitung");
        jPanel1.add(hitung);
        hitung.setBounds(10, 200, 90, 30);

        exit.setText("Keluar");
        jPanel1.add(exit);
        exit.setBounds(340, 200, 80, 30);

        cobalagi.setText("Coba Lagi");
        jPanel1.add(cobalagi);
        cobalagi.setBounds(180, 200, 90, 30);

        jLabel6.setText("Berat Badan Ideal Anda Adalah");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 250, 200, 30);
        jPanel1.add(hbi);
        hbi.setBounds(220, 250, 110, 30);

        jLabel7.setText("kg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 250, 40, 30);

        jLabel8.setText("Hasil Diagnosa Kesehatan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 300, 270, 30);
        jPanel1.add(h1);
        h1.setBounds(10, 330, 410, 30);
        jPanel1.add(h2);
        h2.setBounds(10, 380, 410, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBeratBadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cobalagi;
    private javax.swing.JButton exit;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField hbi;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton l;
    private javax.swing.JTextField n;
    private javax.swing.JTextField t;
    private javax.swing.JRadioButton w;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
